---
- name: Create directory for custom scripts
  file:
    path: "{{ custom_scripts_dir }}"
    state: directory

# If "{{ ansible_user_dir }}/.local" was created by the previous task, it will not receive the correct file permissions.
- file: Correct file permissions in rare cases
    path: "{{ ansible_user_dir }}/.local"
    mode: 0700

- name: Copy custom script templates
  template:
    src: "{{ item }}"
    dest: "{{ custom_scripts_dir }}/{{ (item | basename | regex_replace('(.*)\\.j2', '\\1')| splitext)[0] }}"
    mode: u+x
  with_items: "{{ custom_scripts }}"
