---
# Consult defaults/main.yml to learn about the role variables.
- block:
  - name: Copy over script templates for all users
    template:
      src: "{{ item }}"
      dest: "/usr/local/bin/{{ (item | basename | splitext)[0] }}"
      mode: ugo+x
    with_fileglob: "{{ custom_scripts_for_bin }}"

  - name: Copy over script templates for elevated users
    template:
      src: "{{ item }}"
      dest: "/usr/local/sbin/{{ (item | basename | splitext)[0] }}"
      mode: ugo+x
    with_fileglob: "{{ custom_scripts_for_sbin }}"
  become: true
