---
- block:
  - name: Copy script templates for all users
    template:
      src: "{{ item }}"
      dest: "/usr/local/bin/{{ (item | basename | splitext)[0] }}"
      mode: ugo+x
    with_fileglob: "{{ custom_scripts_for_bin }}"
    when: custom_scripts_for_bin is defined

  - name: Copy script templates for elevated users
    template:
      src: "{{ item }}"
      dest: "/usr/local/sbin/{{ (item | basename | splitext)[0] }}"
      mode: ugo+x
    with_fileglob: "{{ custom_scripts_for_sbin }}"
    when: custom_scripts_for_sbin is defined
  become: true
