---
- name: Copy script templates
  template:
    src: "{{ item[1] }}"
    dest: "{{ custom_scripts[0].dest }}/{{ (item[1] | basename | regex_replace('(.*)\\.j2', '\\1')| splitext)[0] }}"
    owner: "{{ custom_scripts[0].owner | default(omit) }}"
    group: "{{ custom_scripts[0].group | default(omit) }}"
    mode: "{{ custom_scripts[0].mode | default('u+x') }}"
    backup: "{{ custom_scripts[0].backup | default('false')}}"
  with_subelements:
    - "{{ custom_scripts }}"
    - src
  become: true
