---
- name: Copy script templates
  template:
    src: "{{ item }}"
    dest: "{{ custom_scripts_dir | default(ansible_user_dir + '/bin')}}/{{ (item | basename | regex_replace('(.*)\\.j2', '\\1')| splitext)[0] }}"
    mode: "{{ custom_scripts_mode | default('u+x') }}"
  with_items: "{{ custom_scripts }}"
  when: custom_scripts is defined

- name: Copy script templates for elevated users
  template:
    src: "{{ item }}"
    dest: "/usr/local/sbin/{{ (item | basename | regex_replace('(.*)\\.j2', '\\1')| splitext)[0] }}"
    mode: ugo+x
  with_items: "{{ custom_scripts_for_sbin }}"
  when: custom_scripts_for_sbin is defined
  become: true
